### ISSUE TITLE
[Basic React skills needed] Add starting docs

### ISSUE THREAD

**Issue by JPTIZ** [codeisscience/codecompliance-frontend#1]
Although we know it is a React project, it would be nice to add some instructions of how to properly run and serve the website locally so anyone wanting to contribute could have an easy entry-point for testing.

**Comment by ikayz** [comment]
@JPTIZ Should I add them or wait for a contributor?

**Comment by JPTIZ** [comment]
I think you can add them if you want :)

**Comment by JPTIZ** [comment]
Oh, actually #2 seems to address this issue

**Comment by JPTIZ** [comment]
Closed by https://github.com/codeisscience/codecompliance-frontend/commit/46c72d053c7e86d3830df549e8d5249e7fee8c93
