### ISSUE TITLE
Add Tailwind CSS as a framework for frontend

### ISSUE THREAD

**Issue by ikayz** [codeisscience/codecompliance-frontend#3]
Add Tailwind CSS as a dependency to the project and test if it's working using simple components such as buttons or form fields.

**Comment by silenteyesoncode** [comment]
wanna work on it

**Comment by JPTIZ** [comment]
Does #4 close this issue?

**Comment by ikayz** [comment]
@JPTIZ Yes, @joneskj55 worked on this issue
